spring: # Spring configuration
  application: # Application configuration
    name: PharmaScout # Name of the application
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev} # Default profile

  datasource: # Datasource configuration
    hikari: # HikariCP configuration
      maximum-pool-size: 5 # Maximum number of connections in the pool
      idle-timeout: 300000 # Maximum idle time for connection
      connection-timeout: 30000 # Maximum connection timeout
      allow-pool-suspension: true
  task: # Task configuration
    scheduling: # Scheduling configuration
      pool: # Pool configuration
        size: 5 # Maximum number of threads in the pool
  data:
    jpa:
      repositories:
        enabled: true
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss # Date format

server:  # Server configuration
  port: 6969 # Port number
